AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Metrics/AbcSize:
  Max: 32

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Exclude:
    - lib/moose_inventory/config/config.rb
    - lib/moose_inventory/db/db.rb

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/PerceivedComplexity:
  Max: 8

Metrics/BlockLength:
  Exclude:
    - spec/lib/moose_inventory/cli/formatter_spec.rb
    - spec/lib/moose_inventory/cli/host_rm_spec.rb
    - spec/lib/moose_inventory/config/config_spec.rb
    - spec/lib/moose_inventory/db/db_spec.rb
    - spec/lib/moose_inventory/operations/add_hosts_spec.rb
    - spec/lib/moose_inventory/operations/add_groups_spec.rb
    - spec/lib/moose_inventory/operations/add_associations_spec.rb
    - spec/lib/moose_inventory/operations/remove_associations_spec.rb
    - spec/lib/moose_inventory/operations/group_child_relations_spec.rb
    - spec/lib/moose_inventory/operations/remove_groups_spec.rb
    - spec/lib/moose_inventory/operations/add_variables_spec.rb
    - spec/lib/moose_inventory/operations/remove_hosts_spec.rb
    - spec/lib/moose_inventory/operations/remove_variables_spec.rb
    - spec/lib/moose_inventory/operations/query_inventory_spec.rb

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - lib/moose_inventory/config/config.rb

Lint/RescueException:
  Exclude:
    - lib/moose_inventory/db/db.rb
